#' Read plate in txt format generated by Biotek Kc4 software.
#' Files should be from the same experiment and should be provided in the order
#' they were collected.
#' @param files List of file paths.
#' @importFrom dplyr bind_rows
#' @author Ethan Bass
#' @export

read_plate <- function(files){

  ctimes <- file.info(files)$ctime
  if (any(order(ctimes) != seq_along(ctimes))){
    warning("Files do not appear to be created in the specified order. Please
            make sure files are ordered correctly!")
  }

  x<-lapply(files, readLines)

  x <- lapply(seq_along(x), function(i){
    xx <- extract_table(x[[i]])
    xx$file <- files[i]
    xx
  })

  for (i in 2:length(x)){
    x[[i]]$Time <- x[[i]]$Time + max(x[[i-1]]$Time)
  }
  bind_rows(x)
}

#' Extract a single table from Kc4 text file
#'
#' @importFrom purrr map_dfr
#' @importFrom stringr str_split_fixed
#' @importFrom tidyr pivot_longer
#' @author Ethan Bass
#' @noRd
extract_table <- function(df, tidy = TRUE){
  headings<-grep("Table", df)
  x1 <- purrr::map_dfr(seq_len(length(headings)-1), function(i){
    # print(i)
    x <- df[(headings[i]+1):(headings[i+1]-2)]
    x <- stringr::str_split_fixed(x, ";", stringr::str_count(x[1],";")+1)
    colnames(x) <- x[1,]
    x <- x[-1,]
    x[,1] <- fix_time(x[,1])
    x <- suppressWarnings(apply(x, 2, as.numeric))
    x <- as.data.frame(x)
    x$lambda <- stringr::str_split_fixed(df[headings]," ",4)[i,3]
    if (tidy)
      x <- tidyr::pivot_longer(x, cols=2:(ncol(x)-1))
    x
  })
  x1
}

#' @noRd
fix_time <- function(vec){
  sapply(strsplit(vec, ":"), function(x) {
    x <- as.numeric(x)
    x[1] + x[2] / 60
  })
}
